# File: restapp-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: restapp-deployment
  labels:
    app: restapp
  namespace: default
spec:
  replicas: 3
  selector:
    matchLabels:
      app: restapp
  template:
    metadata:
      labels:
        app: restapp
    spec:
      containers:
      - name: restapp
        image: aghosh7123/restimage:latest
        ports:
        - containerPort: 80
---
# Nodeport service to expose the application
apiVersion: v1
kind: Service
metadata:
  name: restapp-service
  namespace: default
spec:
  selector:
    app: restapp
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: NodePort
