# File: restapp-deployment.yaml

apiVersion: apps/v1
kind: Deployment
metadata:
  name: restapp-deployment
  labels:
    app: restapp
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: restapp
  template:
    metadata:
      labels:
        app: restapp
    spec:
      containers:
      - name: restapp
        image: aghosh7123/restimage:latest
        ports:
        - containerPort: 80

---
apiVersion: v1
kind: Rollout
metadata:
  name: restapp-rollout
  namespace: default
spec:
  replicas: 1  # This line is redundant and can be removed
  selector:
    matchLabels:
      app: restapp
  strategy:
    blueGreen:
      activeService: restapp-service
      previewService: restapp-preview-service
      autoPromotionEnabled: true
  template:
    metadata:
      labels:
        app: restapp
    spec:
      containers:
      - name: restapp
        image: aghosh7123/restimage:latest
        ports:
        - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: restapp-service
  namespace: default
spec:
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  selector:
    app: restapp

---
apiVersion: v1
kind: Service
metadata:
  name: restapp-preview-service
  namespace: default
spec:
  ports:
  - protocol: TCP
    port: 8080  # Different port for preview service
    targetPort: 80
  selector:
    app: restapp
